### ISSUE TITLE
Tạo báo cáo số 1

### ISSUE THREAD

**Issue by tungdduy** [tungdduy/funixCP#3]
Phần này là về nhóm các nhà phát triển, ý tưởng ban đầu của đồ án tốt nghiệp nhóm, tổng
quan về các giải pháp tương tự hiện có, tổng quan về các phương pháp hiện có, phác thảo
kinh doanh, các hạn chế của hệ thống hiện tại. Từ những điểm đó, bạn sẽ khai thác sâu hơn
kiến thức /kỹ năng của mình trong chủ đề đã chọn và lợi ích của hệ thống dự kiến.
<Giới thiệu về tài liệu này, cách thức tổ chức và nội dung của nó>

**Comment by giapsoft** [comment]
### I. Báo cáo dự án.
Theo tôi nhớ thì thầy bảo bỏ luôn phần I la mã.
Có nghĩa là bắt đầu thẳng từ mục **1. Tổng quan**
trong phần II của ông bây giờ.
Và bỏ luôn tiêu đề của II. đi nhé
vì tiêu đề của I. không còn thì II. cũng thế.

### Đội dự án
Số điện thoại của tôi là 0976-900-491 nhé anh em.
Không biết làm sao ông lại mò ra số 260910 kia =)))

### 2. Product Background.
Nội dung đã khá ổn. 
Nên đổi cái tên này sang dạng thuần Việt, chỉ chi bất khả kháng mình mới dùng tiếng Anh thôi.
Tôi nghĩ có thể đặt là **Bối cảnh dự án**

### 3. Hệ thống đã tồn tại.
Tôi nghĩ nên phân mục cho từng đối thủ, như là 

- 3.1. GoDee 
- 3.2. Phương Trang
- 3.3. An Vui
- ...

Hoặc không thì lập 1 bảng phân tích những điểm mạnh, yếu của họ.

### 4. Cơ hội kinh doanh
Số liệu thì tổ chức có ok rồi, nhưng cần bổ sung thời điểm nữa  (tháng mấy, năm bao nhiêu)
Mỗi số liệu nên được:
- tóm vào 1 gạch đầu dòng riêng biệt, sẽ dễ quan sát hơn.
- phân đơn vị hàng nghìn để dễ dọc.

**bổ sung ý:** Qua rà soát các đối thủ bên trên, nhận thấy vẫn còn cơ hội rất lớn để tiếp cận toàn bộ thị trường xe khách liên tỉnh tuyến cố định. Vì vậy nhóm chúng tôi quyết định thực hiện đồ án này, như một giải pháp tiện lợi, tiết kiệm chi phí, và phù hợp với đối tượng khách hàng này nhất. 

### 5. Tầm nhìn sản phẩm
Hình như cái ông đang viết là sứ mệnh, không phải tầm nhìn.
- Sứ mệnh là cái lợi ích đem lại cho người sử dụng.
- Tầm nhìn là mức độ ảnh hưởng, là quy mô thị trường.

Tầm nhìn ví dụ:

- 2022: Sản phẩm đi vào hoạt động.
- 2023: Trở thành ứng dụng đặt xe khách cho ít nhất 50 nhà xe ở các tỉnh phía Bắc.
- 2025: Trở thành ứng dụng đặt xe khách ưa chuộng nhất Việt Nam.
- 2027: Ứng dụng đặt xe khách phổ biến nhất Đông Nam Á

### 6. Phạm vi và giới hạn dự án
Chỗ này anh em còn phải bàn nhiều.
Khi đi vào chi tiết sẽ biết chính xác chức năng nào có, chức năng nào không.
Nên tạm thời cứ để đó đã.

### Thắc mắc ngoài lề
Phần đánh version tôi cũng hơi có chút thắc mắc để áp dụng vào project của mình.
theo link https://semver.org/ mà Tùng gửi thì, cách đánh version cho phiên bản tiếp theo như sau:

+ Nếu ông thêm ý: 1.1.0
+ Nếu ông sửa lỗi dấu câu: 1.1.1
+ Nếu ông sửa ý, làm cho ý nghĩa của phần nào đó khác đi: 2.0.0

Có đúng không nhỉ =)))

# Kết
Trên đây là góp của tôi cho report 1, version 1.0.0
Ông làm rất nhanh, tôi hơi bất ngờ.
Viết cũng khá ok, tương đối mạch lạc.
Ông có thể **ok** hoặc **reject** những góp ý này.

Ngoài ra thì cần xem lại chút về dấu câu (khoảng cách, chấm phẩy,...) cho đúng quy phạm đánh máy.

**Comment by tungdduy** [comment]
The report has been submit on 27-May-2021, in loop mail: "Nhắc lịch tiến độ báo cáo tuần 3".
