### ISSUE TITLE
Menu Vé >> hiện vé không thuộc về nhà xe

### ISSUE THREAD

**Issue by tungdduy** [tungdduy/funixCP#37]
![image](https://user-images.githubusercontent.com/42193776/132087239-dd3ddc84-13cf-440e-a7bc-93647e9bc7f2.png)

Login bằng user của nhà xe Thành Bưởi >> menu: Vé >> xem thông tin các vé đặt của nhà xe
Expected:
- Hiện đầy đủ các vé đặt của nhà xe Thành Bưởi
Actual:
- Tất cả vé được hiển thị (vé không thuộc nhà xe Thành Bưởi)

**Comment by giapsoft** [comment]
fixed.
