### ISSUE TITLE
Menu Vé >> Thêm lịch trình để thêm vé

### ISSUE THREAD

**Issue by tungdduy** [tungdduy/funixCP#38]
![image](https://user-images.githubusercontent.com/42193776/132087316-6fdb78c4-30ca-4e84-9dd9-3b8495f9cfa1.png)

Login user: thanhbuoi_admin
Bấm menu Vé >> bấm dấu + >> Chọn thời gian và lịch 
Expected:
- Chỉ hiện lịch trình thuộc nhà xe TB
Actual:
- Tất cả các lịch trình được hiện ra

**Comment by tungdduy** [comment]
![image](https://user-images.githubusercontent.com/42193776/132087599-a66bc766-0e14-43b1-8bbf-46cca53b7983.png)
Sau khi bấm chọn Lưu, dòng Ngày khởi hành bị mất đi

**Comment by tungdduy** [comment]
![image](https://user-images.githubusercontent.com/42193776/132087648-b1a4b660-8c69-4c74-a5d7-9b97b83b432c.png)

Chọn ngày khởi hành và lịch trình > bấm lưu 1 lần
Lặp lại các bước với ngày khởi hành và lịch trình giống bước trên
Expected:
- Chỉ hiện 1 chuyến đi duy nhất
Actual:
- hiện 2 chuyến đi (lặp lại)

**Comment by giapsoft** [comment]
fixed.
