### ISSUE TITLE
Menu xe và lịch trình >> Hiện cả các tuyến đường ko thuộc nhà xe

### ISSUE THREAD

**Issue by tungdduy** [tungdduy/funixCP#39]
![image](https://user-images.githubusercontent.com/42193776/132087415-737d1439-f588-40eb-b79f-c6f97d5b53df.png)
![image](https://user-images.githubusercontent.com/42193776/132087430-12f33ea0-afc0-4d6b-8be2-42a625e297b4.png)

User: thanhbuoi_admin
Menu xe và lịch trình >> Chọn xe >> Thêm lịch trình >> Thêm tuyến đường
Expected:
- Hiện tuyến đường thuộc nhà xe thành bưởi
Actual:
- Tất cả các tuyến đường được hiển thị

**Comment by giapsoft** [comment]
fixed.
