### ISSUE TITLE
Menu Vé >> Không chọn được điểm lên xe (ngoại trừ điểm đầu, cuối)

### ISSUE THREAD

**Issue by tungdduy** [tungdduy/funixCP#40]
![image](https://user-images.githubusercontent.com/42193776/132087773-b27d0c37-4f0c-4647-8e7e-1dce9e55d7fc.png)
![image](https://user-images.githubusercontent.com/42193776/132087822-30e729a5-eadf-4a8c-984d-a977b4b6b164.png)

1: CHọn điểm lên xe (số 1)
2: Chọn điểm xuống xe (số 2)

Expected result:
- Hiện đúng điểm lên, xuống xe
- Khấu trừ giá đúng
Acutal:
- Điểm lên xe, xuống xe luôn là điểm đầu, cuối --> sai
- Giá không được khấu

**Comment by giapsoft** [comment]
fixed.
