### ISSUE TITLE
Menu Tuyến đường >> thừa cột ở bảng

### ISSUE THREAD

**Issue by tungdduy** [tungdduy/funixCP#41]
![image](https://user-images.githubusercontent.com/42193776/132092112-6deeee28-738c-4dd6-938a-6fa280c293cd.png)

User login: thanhbuoi_tongdai (Role: Tổng đài)
Vào Menu >> Tuyến đường
Expected
- Hiện thông tin bảng hợp lý
Actual:
- Thừa 1 cột cuối cùng với các dấu tick ko có chức năng

**Comment by giapsoft** [comment]
fixed.

**Comment by tungdduy** [comment]
![image](https://user-images.githubusercontent.com/42193776/132096275-690aae66-884d-4eb6-94a3-6c5d13aa0c83.png)

Lỗi tương tự với màn hình Menu Xe và Lịch trình >>> Danh sách xe

**Comment by giapsoft** [comment]
fixed.

**Comment by tungdduy** [comment]
![image](https://user-images.githubusercontent.com/42193776/132098966-59da4633-b716-4490-b39d-89aee4e2daae.png)

Lỗi tương tự, refer ảnh đính kèm

**Comment by giapsoft** [comment]
fixed.
