### ISSUE TITLE
Menu Vé >> Danh sách vé không đồng nhất

### ISSUE THREAD

**Issue by tungdduy** [tungdduy/funixCP#43]
![image](https://user-images.githubusercontent.com/42193776/132096592-734a771f-4e6f-462b-8c23-8b4cf93d101a.png)
![image](https://user-images.githubusercontent.com/42193776/132096613-06b7aaed-add9-430e-a2b0-13d9a4d07f9c.png)

**Actual:**
Login as thanhbuoi_admin
Menu Vé >> danh sách vé >> có 1 vé của khách hàng được hiển thị (Hình 1)

Login as thanhbuoi_tongdai
Menu Vé >> danh sách vé >> không có vé nào của khách hàng được hiển thị (Hình 2)

**Expected:**
Danh sách vé giữa 2 role cần thống nhất

**Comment by giapsoft** [comment]
fixed.
