### ISSUE TITLE
Menu >> Vé: lỗi không load được trang

### ISSUE THREAD

**Issue by tungdduy** [tungdduy/funixCP#44]
![image](https://user-images.githubusercontent.com/42193776/132098476-10f81199-3e53-45a3-b16a-cd2664976e43.png)
![image](https://user-images.githubusercontent.com/42193776/132098510-c228a0fb-451f-435d-ba8a-a69aa0039b2c.png)

Login with user: giapsoft (quyền: quản trị hệ thống, không thuộc nhà xe nào)
Menu >> Vé

Expected: Hiện tất cả các vé, phân trang
Actual: Trang trắng

**Comment by giapsoft** [comment]
fixed.
