### ISSUE TITLE
Thêm nhân viên role: Nhân viên xe

### ISSUE THREAD

**Issue by tungdduy** [tungdduy/funixCP#45]
![image](https://user-images.githubusercontent.com/42193776/132098828-072c1bb2-dae5-4ea9-b708-58a29371efa5.png)

Menu Xe & Lịch trình >> chọn xe >> chọn nhân viên 

Expected: Hiện danh sách nhân viên có role: Nhân viên xe
Actual: Hiện cả nhân viên ko có role: Nhân viên xe

**Comment by giapsoft** [comment]
fixed.
