### ISSUE TITLE
Tài khoản của tôi >> Thông tin công ty

### ISSUE THREAD

**Issue by tungdduy** [tungdduy/funixCP#46]
1. 
![image](https://user-images.githubusercontent.com/42193776/132099216-27a78f28-e550-4779-88ae-23ef0c01db4e.png)

Actual: Nhân viên role: Tổng đài, nhân viên xe có thể sửa thông tin nhà xe
Expected: Không được phép sửa

2.
![image](https://user-images.githubusercontent.com/42193776/132099418-fbbd5956-941f-4673-9508-94f81189d01a.png)
![image](https://user-images.githubusercontent.com/42193776/132099423-540e336e-f1fa-47e8-8e46-d1b38c4f7202.png)
![image](https://user-images.githubusercontent.com/42193776/132099429-0d82effb-c5dd-4b16-a396-55835ef01111.png)

Actual: Sau khi nhấn save thông tin (thông báo thành công):
>> Thông tin không được cập nhật khi bấm hủy
>> F5 lại trang, hiện thông tin đúng nhưng lỗi font

Expected:
>> Thông tin tự động hiển thị đúng sau khi bấm hủy
>> Thay button Hủy bằng Đóng
>> Không lỗi font

**Comment by giapsoft** [comment]
fixed.
