### ISSUE TITLE
Tạo vé với Role nhân viên xe

### ISSUE THREAD

**Issue by tungdduy** [tungdduy/funixCP#47]
![image](https://user-images.githubusercontent.com/42193776/132100503-3bb2d042-09b5-404c-8309-8e3708d9a85d.png)

User: thanhbuoi_cx2
Chuyên tuyến: HN - Yên Bái
Vào menu Vé >> Thêm vé, chọn thời gian khởi hành và lịch trình
Expected: Chỉ những lịch trình thuộc về xe HN - YB được hiện
Actual: Hiện cả lịch trình của xe khác mà nhân viên không được

**Comment by giapsoft** [comment]
fixed.
