### ISSUE TITLE
Role Nhân viên xe: nút sửa hiển thị cho lịch 

### ISSUE THREAD

**Issue by tungdduy** [tungdduy/funixCP#48]
Login: thanhbuoi_cx
Menu Xe & Lịch trình >> Chọn Lịch trình của xe 29B1-163.83 >> Bấm vào icon số điểm đi qua
Expected:
- Role ng dùng k được phép sử thông tin lịch trình 
Actual:
- Nút sửa hiển thị cho phép người dùng

**Comment by giapsoft** [comment]
fixed.
