### ISSUE TITLE
Sửa điểm đi qua của lịch trình: Hủy sửa >> dữ liệu sửa hiển thị thay vì dữ liệu cũ

### ISSUE THREAD

**Issue by tungdduy** [tungdduy/funixCP#50]
1. Bấm sửa

![image](https://user-images.githubusercontent.com/42193776/132128757-8452dadf-83ba-4a8e-96d7-f564c853e7b4.png)

2. Sửa thông tin sau đó  bấm quay lại để hủy sửa đổi
![image](https://user-images.githubusercontent.com/42193776/132128795-8f9fa01c-e567-4f4b-90fe-dfd683947470.png)

Acutal:
- Thông tin sửa sau khi hủy vẫn hiển thị
- Nút Lưu vẫn hiển thị
Expected:
- Mọi thông tin quay trở về giá trị cũ trước khi sửa
- Nút lưu không được hiển thị, hiển thị nút sửa

**Comment by giapsoft** [comment]
fixed
